//tag::ref-doc[]
= FTP Source
This source application supports transfer of files using the FTP protocol.
Files are transferred from the `remote` directory to the `local` directory where the app is deployed.
Messages emitted by the source are provided as a byte array by default. However, this can be
customized using the `--mode` option:

- *ref* Provides a `java.io.File` reference
- *lines* Will split files line-by-line and emit a new message for each line
- *contents* The default. Provides the contents of a file as a byte array

When using `--mode=lines`, you can also provide the additional option `--withMarkers=true`.
If set to `true`, the underlying `FileSplitter` will emit additional _start-of-file_ and _end-of-file_ marker messages before and after the actual data.
The payload of these 2 additional marker messages is of type `FileSplitter.FileMarker`. The option `withMarkers` defaults to `false` if not explicitly set.

== Options

The **$$ftp$$** $$source$$ has the following options:

//tag::configuration-properties[]
$$ftp.auto-create-local-dir$$:: $$<documentation missing>$$ *($$Boolean$$, default: `<none>`)*
$$ftp.delete-remote-files$$:: $$<documentation missing>$$ *($$Boolean$$, default: `<none>`)*
$$ftp.filename-pattern$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
$$ftp.filename-regex$$:: $$<documentation missing>$$ *($$Pattern$$, default: `<none>`)*
$$ftp.local-dir$$:: $$<documentation missing>$$ *($$File$$, default: `<none>`)*
$$ftp.preserve-timestamp$$:: $$<documentation missing>$$ *($$Boolean$$, default: `<none>`)*
$$ftp.remote-dir$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
$$ftp.remote-file-separator$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
$$ftp.tmp-file-suffix$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
//end::configuration-properties[]

//end::ref-doc[]
== Build

```
$ mvn clean package
```

