//tag::ref-doc[]
= File Source

This application polls a directory and sends new files or their contents to the output channel.
The file source provides the contents of a File as a byte array by default.
However, this can be customized using the `--mode` option:

- *ref* Provides a `java.io.File` reference
- *lines* Will split files line-by-line and emit a new message for each line
- *contents* The default. Provides the contents of a file as a byte array

When using `--mode=lines`, you can also provide the additional option `--withMarkers=true`.
If set to `true`, the underlying `FileSplitter` will emit additional _start-of-file_ and _end-of-file_ marker messages before and after the actual data.
The payload of these 2 additional marker messages is of type `FileSplitter.FileMarker`. The option `withMarkers` defaults to `false` if not explicitly set.

== Options

The **$$file$$** $$source$$ has the following options:

//tag::configuration-properties[]
$$file.directory$$:: $$The directory to poll for new files.$$ *($$String$$, default: `<none>`)*
$$file.filename-pattern$$:: $$A simple ant pattern to match files.$$ *($$String$$, default: `<none>`)*
$$file.filename-regex$$:: $$A regex pattern to match files.$$ *($$Pattern$$, default: `<none>`)*
$$file.prevent-duplicates$$:: $$Set to true to include an AcceptOnceFileListFilter which prevents duplicates.$$ *($$Boolean$$, default: `true`)*
//end::configuration-properties[]

The `ref` option is useful in some cases in which the file contents are large and it would be more efficient to send the file path.

//end::ref-doc[]

== Build

```
$ mvn clean package
```

