//tag::ref-doc[]
= Amazon S3 Source

This source app supports transfer of files using the Amazon S3 protocol.
Files are transferred from the `remote` directory (S3 bucket) to the `local` directory where the application is deployed.

Messages emitted by the source are provided as a byte array by default. However, this can be
customized using the `--mode` option:

- *ref* Provides a `java.io.File` reference
- *lines* Will split files line-by-line and emit a new message for each line
- *contents* The default. Provides the contents of a file as a byte array

When using `--mode=lines`, you can also provide the additional option `--withMarkers=true`.
If set to `true`, the underlying `FileSplitter` will emit additional _start-of-file_ and _end-of-file_ marker messages before and after the actual data.
The payload of these 2 additional marker messages is of type `FileSplitter.FileMarker`. The option `withMarkers` defaults to `false` if not explicitly set.

== Options

The **$$s3$$** $$source$$ has the following options:
//tag::configuration-properties[]
$$s3.auto-create-local-dir$$:: $$<documentation missing>$$ *($$Boolean$$, default: `<none>`)*
$$s3.delete-remote-files$$:: $$<documentation missing>$$ *($$Boolean$$, default: `<none>`)*
$$s3.filename-pattern$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
$$s3.filename-regex$$:: $$<documentation missing>$$ *($$Pattern$$, default: `<none>`)*
$$s3.local-dir$$:: $$<documentation missing>$$ *($$File$$, default: `<none>`)*
$$s3.preserve-timestamp$$:: $$<documentation missing>$$ *($$Boolean$$, default: `<none>`)*
$$s3.remote-dir$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
$$s3.remote-file-separator$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
$$s3.tmp-file-suffix$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
//end::configuration-properties[]

== Amazon AWS common options

The Amazon S3 Source (as all other Amazon AWS applications) is based on the
https://github.com/spring-cloud/spring-cloud-aws[Spring Cloud AWS] project as a foundation, and its auto-configuration
classes are used automatically by Spring Boot.
Consult their documentation regarding required and useful auto-configuration properties.

Some of them are about AWS credentials:

- cloud.aws.credentials.accessKey
- cloud.aws.credentials.secretKey
- cloud.aws.credentials.instanceProfile
- cloud.aws.credentials.profileName
- cloud.aws.credentials.profilePath

Other are for AWS `Region` definition:

- cloud.aws.region.auto
- cloud.aws.region.static

And for AWS `Stack`:

- cloud.aws.stack.auto
- cloud.aws.stack.name

//end::ref-doc[]
== Build

```
$> mvn package
```
