//tag::ref-doc[]
= SFTP Source

This source app supports transfer of files using the SFTP protocol.
Files are transferred from the `remote` directory to the `local` directory where the application is deployed.

Messages emitted by the source are provided as a byte array by default. However, this can be
customized using the `--mode` option:

- *ref* Provides a `java.io.File` reference
- *lines* Will split files line-by-line and emit a new message for each line
- *contents* The default. Provides the contents of a file as a byte array

When using `--mode=lines`, you can also provide the additional option `--withMarkers=true`.
If set to `true`, the underlying `FileSplitter` will emit additional _start-of-file_ and _end-of-file_ marker messages before and after the actual data.
The payload of these 2 additional marker messages is of type `FileSplitter.FileMarker`. The option `withMarkers` defaults to `false` if not explicitly set.

== Options

The **$$sftp$$** $$source$$ has the following options:

//tag::configuration-properties[]
$$sftp.auto-create-local-dir$$:: $$<documentation missing>$$ *($$Boolean$$, default: `<none>`)*
$$sftp.delete-remote-files$$:: $$<documentation missing>$$ *($$Boolean$$, default: `<none>`)*
$$sftp.filename-pattern$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
$$sftp.filename-regex$$:: $$<documentation missing>$$ *($$Pattern$$, default: `<none>`)*
$$sftp.local-dir$$:: $$<documentation missing>$$ *($$File$$, default: `<none>`)*
$$sftp.preserve-timestamp$$:: $$<documentation missing>$$ *($$Boolean$$, default: `<none>`)*
$$sftp.remote-dir$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
$$sftp.remote-file-separator$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
$$sftp.tmp-file-suffix$$:: $$<documentation missing>$$ *($$String$$, default: `<none>`)*
//end::configuration-properties[]

//end::ref-doc[]
== Build

```
$> mvn package
```
